name: ml-app-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - flask=2.3.2
  - flask-cors=4.0.0
  - pandas=2.1.0
  - numpy=1.26.0
  - scikit-learn=1.3.0
  - matplotlib=3.8.0
  - plotly=5.18.0
  - pip
  - pip:
    - evidently==0.4.15 